import Navbar from '@/app/(componnts)/Navbar'
import './globals.css'
import { Inter,Poppins } from 'next/font/google'
import Link from 'next/link'
import { ThemeProvider } from './(componnts)/ThemeContext'
import DarkModeToggle from './(componnts)/Darkmodetoggle'
const inter = Inter({ subsets: ['latin'] })
const poppins=Poppins({style:"normal",weight:"700",subsets:["latin-ext"]})
export const metadata = {
  title: 'Home App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  let links=[
    {
        id:1,
        title:"about us",
        url:"/about"
    },
    {
        id:2,
        title:"blog",
        url:"/blog"
    },
    {
        id:3,
        title:"contact",
        url:"/contact"
    },
    {
        id:4,
        title:"Dashboard",
        url:"/dashboard"
    },
    {
        id:5,
        title:"Protfolio",
        url:"/protfolio"
    },
]
  return (
    <html lang="en">
      
        <body className='bg-black'>
        <ThemeProvider>
        <div className="container px-4 h-36 flex justify-between items-center text-white">
              <Link className={`${poppins.className} font-sans font-bold text-2xl`} href="/">lamamia</Link>
              <div className="flex items-center gap-10">
              <DarkModeToggle/>
                  {links.map(link=>{
                      return (
                      <div key={link.id}>
                      <Link className="hover:text-lime-800" key={link.id} href={link.url}>{link.title}</Link>
                      </div>)
                  })}
              </div>
        </div> 
          {children}
          </ThemeProvider>
        </body>
    </html>
  )
}
